// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIaxPTBkXxDy9ZyLF5pW5uMXTX32ak3Qg',
    appId: '1:906793786:web:16328fe1c484dd25d9b603',
    messagingSenderId: '906793786',
    projectId: 'fir-auth-competify-47b22',
    authDomain: 'fir-auth-competify-47b22.firebaseapp.com',
    storageBucket: 'fir-auth-competify-47b22.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYbxUteBXtbcDae-8LyRp3akL5cLF-GxY',
    appId: '1:906793786:android:a033e0ed8723f334d9b603',
    messagingSenderId: '906793786',
    projectId: 'fir-auth-competify-47b22',
    storageBucket: 'fir-auth-competify-47b22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8_9bs2MJ6rpenoYeQYa17mjS_0AQBa2I',
    appId: '1:906793786:ios:c80283bce1536138d9b603',
    messagingSenderId: '906793786',
    projectId: 'fir-auth-competify-47b22',
    storageBucket: 'fir-auth-competify-47b22.firebasestorage.app',
    iosBundleId: 'com.example.competifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8_9bs2MJ6rpenoYeQYa17mjS_0AQBa2I',
    appId: '1:906793786:ios:c80283bce1536138d9b603',
    messagingSenderId: '906793786',
    projectId: 'fir-auth-competify-47b22',
    storageBucket: 'fir-auth-competify-47b22.firebasestorage.app',
    iosBundleId: 'com.example.competifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIaxPTBkXxDy9ZyLF5pW5uMXTX32ak3Qg',
    appId: '1:906793786:web:5496f24a6022c7bed9b603',
    messagingSenderId: '906793786',
    projectId: 'fir-auth-competify-47b22',
    authDomain: 'fir-auth-competify-47b22.firebaseapp.com',
    storageBucket: 'fir-auth-competify-47b22.firebasestorage.app',
  );
}
